# .github/workflows/price_tracker.yml

name: Monitor de Preços Diário

on:
  workflow_dispatch:
  schedule:
    - cron: '0 9,21 * * *'

permissions:
  contents: write

jobs:
  scrape-prices:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Rodar o script de scraping

        run: python src/tracker.py || true
        env:
          SCRAPFLY_API_KEY: ${{ secrets.SCRAPFLY_API_KEY }}

      # PASSO NOVO E IMPORTANTE PARA DEPURAR
      - name: Salvar HTML de debug como Artefato
        # Este passo só será executado se o arquivo de debug existir
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: html-debug-output
          path: scrapfly_output.html

      - name: Fazer commit dos novos preços
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          # Adiciona todos os arquivos na pasta data (products.json e price_history.csv)
          git add data/*
          # Faz o commit apenas se houver mudanças
          git diff --staged --quiet || git commit -m "Atualiza histórico de preços - $(date)"
          git push